all: exe

exe: 151044009_Sevval_MEHDER.o
	gcc 151044009_Sevval_MEHDER.o -o listdir


151044009_Sevval_MEHDER.o: 151044009_Sevval_MEHDER.c
	gcc -c -ansi -pedantic-errors 151044009_Sevval_MEHDER.c -Wall

clean:
	rm *.o listdir
	clear 
